CREATE TABLE nutriscore.id (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    mail_address VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);